In [1]:
import pandas as pd

In [24]:
# Q1. Pandas version

pd.__version__

'2.3.2'

In [3]:
#getting the csv data

!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-24 13:32:38--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  3.24MB/s    in 0.3s    

2025-09-24 13:32:38 (3.24 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [4]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [23]:
# Q2. Records count

df.shape[0]

9704

In [17]:
# Q3. Fuel types

df["fuel_type"].nunique()

2

In [21]:
# Q4. Missing values

df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [20]:
# Q5. Max fuel efficiency

asia_df = df[df["origin"]=="Asia"]
asia_df["fuel_efficiency_mpg"].max()



23.759122836520497

In [25]:
# Q6. Median value of horsepower

# 1. Find the median value of horsepower column in the dataset

df['horsepower'].median()

149.0

In [30]:
# 2. Next, calculate the most frequent value of the same horsepower column.

freq_value = df['horsepower'].value_counts().idxmax()
freq_value

np.float64(152.0)

In [31]:
# 3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

df['horsepower'].fillna(freq_value, inplace=True)

# checking if any missing values still exist

df['horsepower'].isnull().sum()

/tmp/ipykernel_13810/2783533145.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(freq_value, inplace=True)


np.int64(0)

In [33]:
# 4. Calculate the median value of horsepower once again.

df['horsepower'].median()  # median value is diff from before - increased

152.0

In [42]:
# Q7. Sum of weights

# 1. Select 7  cars from Asia , with only columns vehicle_weight and model_year

asia_cars_df = df[df['origin']=='Asia'][['vehicle_weight','model_year']].head(7)

In [43]:
asia_cars_df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [44]:
import numpy as np

In [56]:
# 4. Convert df to numpy arr X
X = asia_cars_df.to_numpy()
print(X)

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]


In [55]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X

XTX = X.T @ X
print(XTX)

[[62248334.33150762 41431216.50732678]
 [41431216.50732678 28373339.        ]]


In [57]:
# 6. invert XTX

XTX_inv = np.linalg.inv(XTX)

In [58]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [59]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [62]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

z = XTX_inv @ X.T
w = z @ y
w

array([0.01386421, 0.5049067 ])

In [63]:
# 9 .What's the sum of all the elements of the result?
np.sum(w)

np.float64(0.5187709081074007)